version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=insightbot
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  querydb:
    image: postgres:latest
    environment:
      POSTGRES_DB: querydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - querydb_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/insightbot
      - DATABASE_QUERY_URL=postgresql://user:password@querydb:5432/querydb
      - GROQ_API_KEY=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
    depends_on:
      - db
      - querydb

  client:
    build: ./client
    volumes:
      - ./client:/app
    ports:
      - "5175:5173"
    command: npm run dev -- --host

volumes:
  postgres_data:
  querydb_data:
